

CREATE DATABASE AUG23;


USE AUG23;

CREATE TABLE CUSTOMERS(
C_ID INT IDENTITY(101,1) PRIMARY KEY,
C_NAME VARCHAR(55) NOT NULL,
C_CITY VARCHAR(55),
C_PHONE VARCHAR(14),
C_EMAIL VARCHAR(55),
);

ALTER TABLE CUSTOMERS
ADD COUNTRY VARCHAR(55);

INSERT INTO CUSTOMERS(C_NAME,C_CITY,C_PHONE,C_EMAIL)
VALUES('RAHUL CHY','KOLKATA','1800 8721 5502','RAHUL@MAIL.COM'),
('VARUN NAYAK','NEW DELHI','+91 1787 11661','VARUN@MAIL.COM');

INSERT INTO CUSTOMERS(C_NAME,C_CITY,C_PHONE,C_EMAIL)
VALUES('NAMAN OJHA','BANGLORE','1800 8628 8474','NAMAN@MAIL.COM'),
('KUSHI BILLORE','BHOPAL','+91 7623 23452','KUSHI@MAIL.COM'),
('VIDUSHUI','INDORE','+91 7623 45554','VIDUSHI@MAIL.COM'),
('RAMAN HARSHA','SINDHU','1800 8628 2344','RAMAN@MAIL.COM');

SELECT * FROM CUSTOMERS;

UPDATE CUSTOMERS 
SET COUNTRY = 'INDIA';

SELECT * FROM CUSTOMERS;


INSERT INTO CUSTOMERS(C_NAME,C_CITY,C_PHONE,C_EMAIL,COUNTRY)
VALUES('JOHN DOE','TORONTO','5544 7766 8899','JDOE@MAIL.COM','CANADA'),
('SATYA NADELA','ALASKA','+91 7623 23452','SATYA@MAIL.COM','USA'),
('STARK','BERLIN','+91 7623 45554','STARK@MAIL.COM','SPAIN'),
('JOHN PARKER','HO CHIN MIN CITY','1800 8628 2344','PARKER1@MAIL.COM','VIETNAM');

SELECT * FROM CUSTOMERS;

SELECT * FROM CUSTOMERS WHERE NOT COUNTRY = 'INDIA';

SELECT * FROM CUSTOMERS WHERE COUNTRY='USA' OR COUNTRY = 'SPAIN';

SELECT * FROM CUSTOMERS WHERE COUNTRY = 'VIETNAM' AND C_NAME = 'JOHN PARKER';


SELECT * FROM CUSTOMERS
ORDER BY C_ID ASC;

SELECT * FROM CUSTOMERS
ORDER BY C_ID DESC;

SELECT * FROM CUSTOMERS
WHERE C_ID = 103;

CREATE TABLE ORDERS(
O_ID INT IDENTITY(51,1) PRIMARY KEY,
O_NAME VARCHAR(55),
O_DATETIME DATETIME,
LAST_UPDATE TIMESTAMP,
CUST_ID INT
);


ALTER TABLE ORDERS
ADD FOREIGN KEY(CUST_ID) REFERENCES CUSTOMERS(C_ID);

ALTER TABLE ORDERS
ADD I_ID INT FOREIGN KEY REFERENCES ITEMS(I_ID);

ALTER TABLE ORDERS
DROP COLUMN O_NAME;

INSERT INTO ORDERS(O_DATETIME,CUST_ID,I_ID)
VALUES(GETDATE(),101,151),
(GETDATE(),102,151);

CREATE TABLE ITEMS(
I_ID INT IDENTITY(151,1) PRIMARY KEY,
I_NAME VARCHAR(55),
I_PRICE MONEY
);

INSERT INTO ITEMS(I_NAME,I_PRICE)
VALUES('COCA COLA 750ML',40),
('AMUL BUTTER',120),
('AATA',250),
('MILK',45),
('TRIMMER',699),
('T-SHIRT',499);

SELECT * FROM CUSTOMERS;
SELECT * FROM ITEMS;

SELECT * FROM ORDERS;


SELECT C_NAME,C_CITY,I_NAME,I_PRICE FROM CUSTOMERS
JOIN ORDERS ON CUSTOMERS.C_ID = ORDERS.CUST_ID
JOIN ITEMS ON ITEMS.I_ID = ORDERS.I_ID;


/* 23 AUGUST 2023 CLASS */

-- TOPICS NAME START FROM HERE
-- DELETE AND UPDATE FROM THE TABLE

-- CREATE TABLE EMPLOYEE1

CREATE TABLE EMPLOYEE1(
EMP_ID INT IDENTITY(101,1) PRIMARY KEY,
EMP_NAME VARCHAR(55),
EMP_AGE INT,
EMP_GENDER VARCHAR(10),
EMP_ADDRESS VARCHAR(55)
);

-- INSERT VALUES IN EMPLOYEE1 TABLE 
INSERT INTO EMPLOYEE1(EMP_NAME,EMP_AGE,EMP_GENDER,EMP_ADDRESS)
VALUES('MOHAN YADAV',22,'MALE','ROAD NUMBER 1 SHANTI NIKETAN BHOPAL MADHYA PRADESH'),
('LALU YADAV',56,'FEMALE','GUMBAJ ROAD PATNA BIHAR'),
('NITISH KUMAR',62,'MALE','NEW TOWN KOLKATA WEST BENGAL');

INSERT INTO EMPLOYEE1(EMP_NAME,EMP_AGE,EMP_GENDER,EMP_ADDRESS)
VALUES('MAMTA BANARJEE',22,'FEMALE','KOLKATA'),
('MULAYAM YADAV',56,'FEMALE','UTTAR PRADESH'),
('NARENDRA MODI',85,'MALE','GUJRAT'),
('MANMOHAN SINGH',67,'MALE','PUNJAB'),
('NITIN',67,'MALE','UTTRAKHAND'),
('JAYA BACHAN',89,'FEMALE','MUMBAI'),
('JAYA KISHORE',56,'FEMALE','UTTAR PRADESH');
-- GETTING ALL THE VALUE

SELECT * FROM EMPLOYEE1;

-- UPDATE THE EMPLOYEE1 TABLE VALUES

UPDATE EMPLOYEE1 SET EMP_GENDER = 'MALE' WHERE EMP_ID = 102;

UPDATE EMPLOYEE1 SET EMP_ADDRESS = 'SECTOR -2 KANCHI ROAD PATNA BIHAR' WHERE EMp_ID = 103;


-- DELETE EMPLOYEE1 VALUES

DELETE FROM EMPLOYEE1 WHERE EMP_ID = 101;

DELETE EMPLOYEE1 WHERE EMP_ID = 102;

-- FIND TOP 2 VALUES FROM THE TABLE

SELECT TOP 2* FROM EMPLOYEE1;

SELECT TOP 2* FROM EMPLOYEE1 WHERE EMP_GENDER = 'FEMALE';

-- FIND TOP 50% FROM THE TABLE

SELECT TOP 50 PERCENT * FROM EMPLOYEE1;

-- SELECT TOP 50 % WHOSE NAME IS LALU YADAV

SELECT TOP 50 PERCENT * FROM EMPLOYEE1 WHERE EMP_NAME = 'NITISH KUMAR';

SELECT TOP 50 PERCENT * FROM EMPLOYEE1 WHERE EMP_GENDER = 'FEMALE';

SELECT TOP 50 PERCENT * FROM EMPLOYEE1 WHERE EMP_NAME = 'LALU YADAV' AND EMP_GENDER = 'FEMALE';

-- ALTER THE NAME CHANGE TO TEXT TYPE

ALTER TABLE EMPLOYEE1
ALTER COLUMN EMP_NAME TEXT;


ALTER TABLE EMPLOYEE1
ALTER COLUMN EMP_ADDRESS TEXT;

-- READ THE DATA

SELECT * FROM EMPLOYEE1;


/* ******************************************************** FILTER THE VALUES ******************************************* */


-- GET THE TOP 2 VALUES FROM THE TABLE

SELECT TOP 2* FROM EMPLOYEE1;

SELECT TOP 50 PERCENT * FROM EMPLOYEE1;

-- FILTER TEXT 
SELECT TOP 2* FROM EMPLOYEE1 WHERE EMP_ADDRESS LIKE 'UTTAR PRADESH';

-- FILTER STRING BY FIRST LETTER

SELECT TOP 2* FROM EMPLOYEE1 WHERE EMP_ADDRESS LIKE 'G%';

SELECT * FROM EMPLOYEE1 WHERE EMP_NAME LIKE 'N%';

-- FILTER FROM THE END

SELECT TOP 2* FROM EMPLOYEE1 WHERE EMP_ADDRESS LIKE '%BIHAR';

-- FINDS ALL THE VALUES THAT HAVE B AT ANY PLACE

SELECT * FROM EMPLOYEE1 WHERE EMP_ADDRESS LIKE '%B%';

-- FINDS ALL THE VALUE THAT STARTS WITH R AND ENDS WITH H

SELECT * FROM EMPLOYEE1 WHERE EMP_ADDRESS LIKE 'R%H';

-- FINDS ALL THE VALE THAT HAVE O AT SECOND COLUMN

SELECT * FROM EMPLOYEE1 WHERE EMP_ADDRESS LIKE '_O%';

-- SELECT ALL THE VAUES THAT DOESN'T HAVE R AT THE BEGINING

SELECT * FROM EMPLOYEE1 WHERE EMP_ADDRESS NOT LIKE 'R%';

-- SELECT ALL THE VALUES THAT HAVE PUNJAB IN THE STARTING

SELECT * FROM EMPLOYEE1 WHERE EMP_ADDRESS LIKE 'PUNJAB%';



-- CREATING A TABLE NAMED EMPLOYEE2

CREATE TABLE EMPLOYEE2(
EMO_ID INT IDENTITY(1,1),
EMP_NAME VARCHAR(22),
EMP_CITY VARCHAR(22),
EMP_STATE VARCHAR(22),
EMP_COUNTRY VARCHAR(22)
);

INSERT INTO EMPLOYEE2(EMP_NAME,EMP_CITY,EMP_STATE,EMP_COUNTRY)
VALUES('RAJAN','DARBHANGA','BIHAR','INDIA'),
('RAHUL','BHAGALPUR','BIHAR','INDIA'),
('MANOJ','ROHTAS','BIHAR','INDIA'),
('SAKSHI','MADHUBANI','BIHAR','INDIA'),
('MANOHAR','PATNA','BIHAR','INDIA'),
('JOHN DOE','NYC','NEW YORK','USA'),
('GEPPY DOE','HO CHI MIN CITY','MIN CITY','VIETNAM'),
('GRREMY DOE','KATHMANDU','KATHMANDU','NEPAL'),
('KUSHI','JANAKPUR','KATHMANDU','NEPAL');

SELECT * FROM EMPLOYEE2;

-- GET 3RD ROW VALUE FROM THE COLUMN WITHOUT USING ID
-- OFFSET MEANS IGNORE FIRST N ROWS

SELECT * FROM EMPLOYEE2 ORDER BY EMO_ID OFFSET 2 ROWS FETCH NEXT 1 ROW ONLY;



--  CREATE A NEW TABLE EMPLOYEE3

CREATE TABLE EMPLOYEE3(
EMP_ID INT IDENTITY(1,1) PRIMARY KEY,
EMP_NAME VARCHAR(22),
EMP_SALARY MONEY,
EMP_AGE INT
);

INSERT INTO EMPLOYEE3(EMP_NAME,EMP_SALARY,EMP_AGE)
VALUES('ROHAN NANDA',34000,22),
('MANOJ VERMA',46000,20),
('LALU YADAV',20000,24),
('NARENDRA MODI',22000,56);

-- GET ALL THE DATA

SELECT * FROM EMPLOYEE3;

-- FIND THE TOTAL EMPLOYEE IN THE TABLE

SELECT COUNT(*) FROM EMPLOYEE3;

-- SUM OF THE SALARY OF THE EMPLOYEE

SELECT SUM(EMP_SALARY) FROM EMPLOYEE3;

-- AVERAGE OF THE SALARY OF THE EMPLOYEE

SELECT AVG(EMP_SALARY) FROM EMPLOYEE3;


DROP TABLE EMPLOYEE3;
--------------------------------------------- IMPROVEMENT IN THE QUERY
-- CREATING A TABLE NAMED AS EMPLOYEE4
CREATE TABLE EMPLOYEE4(
EMP_ID INT IDENTITY PRIMARY KEY,
EMP_NAME VARCHAR(22),
EMP_SALARY MONEY,
EMP_AGE INT
);
-- INSERTING ALL THE VALUES INTO THE TABLE

INSERT INTO EMPLOYEE4(EMP_NAME,EMP_SALARY,EMP_AGE)
VALUES ('AJAY',12000,22),
('VIJAY',18000,18),
('NILESH',26000,19),
('MUKESH',28000,22),
('SURESH',67000,36),
('SUKESH',77120,46),
('UMESH',34000,56);

-- GETTING ALL THE SALARY
SELECT * FROM EMPLOYEE4;

-- THIS IS PROBLEM EVERY TIME WE HAVE TO USE EMP_ID AND OR KEYWORD
SELECT * FROM EMPLOYEE4 WHERE EMP_ID = 1 OR EMP_ID = 2;

-- THIS IS THE SOLUTION
SELECT * FROM EMPLOYEE4 WHERE EMP_ID IN(1,2);

-- THE RANGE OF SALARY WE HAVE TO FIND
SELECT * FROM EMPLOYEE4 WHERE EMP_SALARY > 20000 AND EMP_SALARY < 50000;

-- THROUGH THIS WE ARE ALSO FINDING THE RANGE OF THE SALARY
SELECT * FROM EMPLOYEE4 WHERE EMP_SALARY BETWEEN 25000 AND 50000;


-- CREATE A TABLE BJP

CREATE TABLE BJP(
B_ID INT IDENTITY(101,1) PRIMARY KEY,
NAME VARCHAR(22),
AGE INT
);
-- CREATE A TABLE CONGRESS
CREATE TABLE CONGRESS(
C_ID INT IDENTITY(201,1) PRIMARY KEY,
NAME VARCHAR(22),
AGE INT
);


INSERT INTO BJP(NAME)
VALUES('NARENDRA MODI',56),('YOGI ADITYANATH',48);

INSERT INTO CONGRESS(NAME,AGE)
VALUES('RAHUL GANDHI',22),('SONIA GANDHI',28),('MANMOHAN SINGH',45);

SELECT * FROM CONGRESS;
SELECT * FROM BJP;

-- ADD BOTH OF THE COLUMN USING UNION

SELECT * FROM CONGRESS UNION SELECT * FROM BJP;

SELECT * FROM BJP UNION SELECT * FROM CONGRESS;


INSERT INTO BJP(NAME,AGE)
VALUES('NARENDRA MODI',32);


-- UNION USE CASE 
-- IN UNION WE WILL NOT GET DUPLICATE VALUE
SELECT NAME FROM BJP UNION SELECT NAME FROM CONGRESS;

-- UNION ALL USE CASE 
-- IN UNION ALL WE GET OUTPUT OF DUPLICATE VALUE ALSO
SELECT NAME FROM BJP UNION ALL SELECT NAME FROM CONGRESS;


-- TABLE1
CREATE TABLE B1(
ID INT IDENTITY(1,1) PRIMARY KEY,
NAME VARCHAR(22),
AGE INT,
T_NAME VARCHAR(22)
);

CREATE TABLE B2(
ID INT IDENTITY(20,1) PRIMARY KEY,
NAME VARCHAR(22),
AGE INT
);

INSERT INTO B1(NAME,AGE,T_NAME)
VALUES('AJAY',22,'MANOJ'),
('VIJAY',26,'MANOJ');


INSERT INTO B2(NAME,AGE)
VALUES('RAHUL',33),
('MAHUL',36);

SELECT * FROM B1;

SELECT * FROM B2;


SELECT * FROM B1  OUTERUNION SELECT * FROM B2;
