

CREATE DATABASE AUG23;


USE AUG23;

CREATE TABLE CUSTOMERS(
C_ID INT IDENTITY(101,1) PRIMARY KEY,
C_NAME VARCHAR(55) NOT NULL,
C_CITY VARCHAR(55),
C_PHONE VARCHAR(14),
C_EMAIL VARCHAR(55),
);

ALTER TABLE CUSTOMERS
ADD COUNTRY VARCHAR(55);

INSERT INTO CUSTOMERS(C_NAME,C_CITY,C_PHONE,C_EMAIL)
VALUES('RAHUL CHY','KOLKATA','1800 8721 5502','RAHUL@MAIL.COM'),
('VARUN NAYAK','NEW DELHI','+91 1787 11661','VARUN@MAIL.COM');

INSERT INTO CUSTOMERS(C_NAME,C_CITY,C_PHONE,C_EMAIL)
VALUES('NAMAN OJHA','BANGLORE','1800 8628 8474','NAMAN@MAIL.COM'),
('KUSHI BILLORE','BHOPAL','+91 7623 23452','KUSHI@MAIL.COM'),
('VIDUSHUI','INDORE','+91 7623 45554','VIDUSHI@MAIL.COM'),
('RAMAN HARSHA','SINDHU','1800 8628 2344','RAMAN@MAIL.COM');

SELECT * FROM CUSTOMERS;

UPDATE CUSTOMERS 
SET COUNTRY = 'INDIA';

SELECT * FROM CUSTOMERS;


INSERT INTO CUSTOMERS(C_NAME,C_CITY,C_PHONE,C_EMAIL,COUNTRY)
VALUES('JOHN DOE','TORONTO','5544 7766 8899','JDOE@MAIL.COM','CANADA'),
('SATYA NADELA','ALASKA','+91 7623 23452','SATYA@MAIL.COM','USA'),
('STARK','BERLIN','+91 7623 45554','STARK@MAIL.COM','SPAIN'),
('JOHN PARKER','HO CHIN MIN CITY','1800 8628 2344','PARKER1@MAIL.COM','VIETNAM');

SELECT * FROM CUSTOMERS;

SELECT * FROM CUSTOMERS WHERE NOT COUNTRY = 'INDIA';

SELECT * FROM CUSTOMERS WHERE COUNTRY='USA' OR COUNTRY = 'SPAIN';

SELECT * FROM CUSTOMERS WHERE COUNTRY = 'VIETNAM' AND C_NAME = 'JOHN PARKER';


SELECT * FROM CUSTOMERS
ORDER BY C_ID ASC;

SELECT * FROM CUSTOMERS
ORDER BY C_ID DESC;

SELECT * FROM CUSTOMERS
WHERE C_ID = 103;

CREATE TABLE ORDERS(
O_ID INT IDENTITY(51,1) PRIMARY KEY,
O_NAME VARCHAR(55),
O_DATETIME DATETIME,
LAST_UPDATE TIMESTAMP,
CUST_ID INT
);


ALTER TABLE ORDERS
ADD FOREIGN KEY(CUST_ID) REFERENCES CUSTOMERS(C_ID);

ALTER TABLE ORDERS
ADD I_ID INT FOREIGN KEY REFERENCES ITEMS(I_ID);

ALTER TABLE ORDERS
DROP COLUMN O_NAME;

INSERT INTO ORDERS(O_DATETIME,CUST_ID,I_ID)
VALUES(GETDATE(),101,151),
(GETDATE(),102,151);

CREATE TABLE ITEMS(
I_ID INT IDENTITY(151,1) PRIMARY KEY,
I_NAME VARCHAR(55),
I_PRICE MONEY
);

INSERT INTO ITEMS(I_NAME,I_PRICE)
VALUES('COCA COLA 750ML',40),
('AMUL BUTTER',120),
('AATA',250),
('MILK',45),
('TRIMMER',699),
('T-SHIRT',499);

SELECT * FROM CUSTOMERS;
SELECT * FROM ITEMS;

SELECT * FROM ORDERS;


SELECT C_NAME,C_CITY,I_NAME,I_PRICE FROM CUSTOMERS
JOIN ORDERS ON CUSTOMERS.C_ID = ORDERS.CUST_ID
JOIN ITEMS ON ITEMS.I_ID = ORDERS.I_ID;


/* 23 AUGUST 2023 CLASS */

-- TOPICS NAME START FROM HERE
-- DELETE AND UPDATE FROM THE TABLE

-- CREATE TABLE EMPLOYEE1

CREATE TABLE EMPLOYEE1(
EMP_ID INT IDENTITY(101,1) PRIMARY KEY,
EMP_NAME VARCHAR(55),
EMP_AGE INT,
EMP_GENDER VARCHAR(10),
EMP_ADDRESS VARCHAR(55)
);

-- INSERT VALUES IN EMPLOYEE1 TABLE 
INSERT INTO EMPLOYEE1(EMP_NAME,EMP_AGE,EMP_GENDER,EMP_ADDRESS)
VALUES('MOHAN YADAV',22,'MALE','ROAD NUMBER 1 SHANTI NIKETAN BHOPAL MADHYA PRADESH'),
('LALU YADAV',56,'FEMALE','GUMBAJ ROAD PATNA BIHAR'),
('NITISH KUMAR',62,'MALE','NEW TOWN KOLKATA WEST BENGAL');

INSERT INTO EMPLOYEE1(EMP_NAME,EMP_AGE,EMP_GENDER,EMP_ADDRESS)
VALUES('MAMTA BANARJEE',22,'FEMALE','KOLKATA'),
('MULAYAM YADAV',56,'FEMALE','UTTAR PRADESH'),
('NARENDRA MODI',85,'MALE','GUJRAT'),
('MANMOHAN SINGH',67,'MALE','PUNJAB'),
('NITIN',67,'MALE','UTTRAKHAND'),
('JAYA BACHAN',89,'FEMALE','MUMBAI'),
('JAYA KISHORE',56,'FEMALE','UTTAR PRADESH');
-- GETTING ALL THE VALUE

SELECT * FROM EMPLOYEE1;

-- UPDATE THE EMPLOYEE1 TABLE VALUES

UPDATE EMPLOYEE1 SET EMP_GENDER = 'MALE' WHERE EMP_ID = 102;

UPDATE EMPLOYEE1 SET EMP_ADDRESS = 'SECTOR -2 KANCHI ROAD PATNA BIHAR' WHERE EMp_ID = 103;


-- DELETE EMPLOYEE1 VALUES

DELETE FROM EMPLOYEE1 WHERE EMP_ID = 101;

DELETE EMPLOYEE1 WHERE EMP_ID = 102;

-- FIND TOP 2 VALUES FROM THE TABLE

SELECT TOP 2* FROM EMPLOYEE1;

SELECT TOP 2* FROM EMPLOYEE1 WHERE EMP_GENDER = 'FEMALE';

-- FIND TOP 50% FROM THE TABLE

SELECT TOP 50 PERCENT * FROM EMPLOYEE1;

-- SELECT TOP 50 % WHOSE NAME IS LALU YADAV

SELECT TOP 50 PERCENT * FROM EMPLOYEE1 WHERE EMP_NAME = 'NITISH KUMAR';

SELECT TOP 50 PERCENT * FROM EMPLOYEE1 WHERE EMP_GENDER = 'FEMALE';

SELECT TOP 50 PERCENT * FROM EMPLOYEE1 WHERE EMP_NAME = 'LALU YADAV' AND EMP_GENDER = 'FEMALE';

-- ALTER THE NAME CHANGE TO TEXT TYPE

ALTER TABLE EMPLOYEE1
ALTER COLUMN EMP_NAME TEXT;


ALTER TABLE EMPLOYEE1
ALTER COLUMN EMP_ADDRESS TEXT;

-- READ THE DATA

SELECT * FROM EMPLOYEE1;


/* ******************************************************** FILTER THE VALUES ******************************************* */


-- GET THE TOP 2 VALUES FROM THE TABLE

SELECT TOP 2* FROM EMPLOYEE1;

SELECT TOP 50 PERCENT * FROM EMPLOYEE1;

-- FILTER TEXT 
SELECT TOP 2* FROM EMPLOYEE1 WHERE EMP_ADDRESS LIKE 'UTTAR PRADESH';

-- FILTER STRING BY FIRST LETTER

SELECT TOP 2* FROM EMPLOYEE1 WHERE EMP_ADDRESS LIKE 'G%';

SELECT * FROM EMPLOYEE1 WHERE EMP_NAME LIKE 'N%';

-- FILTER FROM THE END

SELECT TOP 2* FROM EMPLOYEE1 WHERE EMP_ADDRESS LIKE '%BIHAR';

-- FINDS ALL THE VALUES THAT HAVE B AT ANY PLACE

SELECT * FROM EMPLOYEE1 WHERE EMP_ADDRESS LIKE '%B%';

-- FINDS ALL THE VALUE THAT STARTS WITH R AND ENDS WITH H

SELECT * FROM EMPLOYEE1 WHERE EMP_ADDRESS LIKE 'R%H';

-- FINDS ALL THE VALE THAT HAVE O AT SECOND COLUMN

SELECT * FROM EMPLOYEE1 WHERE EMP_ADDRESS LIKE '_O%';

-- SELECT ALL THE VAUES THAT DOESN'T HAVE R AT THE BEGINING

SELECT * FROM EMPLOYEE1 WHERE EMP_ADDRESS NOT LIKE 'R%';

-- SELECT ALL THE VALUES THAT HAVE PUNJAB IN THE STARTING

SELECT * FROM EMPLOYEE1 WHERE EMP_ADDRESS LIKE 'PUNJAB%';