

CREATE DATABASE QUESTION2;

USE QUESTION2;

-- CREATE TABLE EMPLOYEE

CREATE TABLE EMPLOYEE(
EMP_ID INT IDENTITY(111,1),
EMP_NAME VARCHAR(55),
PRIMARY KEY(EMP_ID,EMP_NAME)
);

-- CREATE SALARY TABLE

CREATE TABLE SALARY(
S_ID INT IDENTITY(21,1) PRIMARY KEY,
EMP_ID INT,
EMP_NAME VARCHAR(55),
SALARY MONEY,
FOREIGN KEY (EMP_ID,EMP_NAME) REFERENCES EMPLOYEE(EMP_ID,EMP_NAME)
);
-- INSETING VALUE IN EMPLOYEE TABLE

INSERT INTO EMPLOYEE(EMP_NAME) VALUES('AJAY');

SELECT * FROM EMPLOYEE;

-- INSERTING VALUES IN SALARY 

INSERT INTO SALARY(EMP_ID,EMP_NAME,SALARY) VALUES(111,'AJAY',52000);


SELECT * FROM SALARY;