
/* CREATING TABLE FOR REGISTER */

CREATE TABLE R(
ID INT IDENTITY(1,1),
USERNAME VARCHAR(55),
PASSWORD VARCHAR(55)
);

/* INSERTING VALUE IN R */

INSERT INTO R(USERNAME,PASSWORD) VALUES
('USER1','1234'),
('USER2','1234');

/* PRINT FROM R */
SELECT * FROM R;
/*ADD COLUMN NAME*/
ALTER TABLE R
ADD NAME VARCHAR(55);
/*PRINT EVERYTHING FROM R*/
SELECT * FROM R;
/*UPDATE NAME COLUMN IN R*/
UPDATE R
SET NAME ='MY USER 1' WHERE ID = 1;
/*PRINTING FROM R*/
SELECT * FROM R;


/*ALTERING THE TABLE AGAIN*/

ALTER TABLE R
ADD GENDER VARCHAR(6);

/*UPDATE THE COLUMN*/

UPDATE  R
SET GENDER = 'FEMALE'
WHERE ID = 2;

SELECT * FROM R;

/* ADD AGE*/

ALTER TABLE R
ADD AGE INT;

/*UPDATE VALUE*/

UPDATE R SET AGE = 18 WHERE ID =1;

SELECT * FROM R;

/*CHANGE DATATYPE*/

ALTER TABLE R
ALTER COLUMN AGE VARCHAR(10);
SELECT * FROM R;

/*CREATING A COLUMN NAMED AS U*/
ALTER TABLE R
ADD U VARCHAR(10);

/*DROPING THE COLUMN NAMED AS U*/
ALTER TABLE R
DROP COLUMN U;
/*ADD THE COLUMN NAMED Y*/
ALTER TABLE R
ADD Y VARCHAR(10);

/*CHANGE THE DATATYPE OF THE COLUMN NAMED Y*/
ALTER TABLE R
ALTER COLUMN Y INT;

SELECT * FROM R;
/*DROP THE COLUMN NAMED AS Y*/
ALTER TABLE R
DROP COLUMN Y;