/* USING THE CREATED DATABASE */
USE ABHINAV;

/* FINDING ALL THE TABLES FROM THE DATABASE */

SELECT * FROM SYS.TABLES;

/* DROPPING MULTIPLE TABLES */

DROP TABLE video,register,demo_table,SIGNUP;

/* CREATING THE TABLE NAMED EMPLOYEE */

CREATE TABLE EMPLOYEE(
ID INT IDENTITY(5555,1) PRIMARY KEY,
NAME VARCHAR(100),
EMAIL VARCHAR(55)
);

/* INSERTING SINGLE VALUE IN THE TABLE */

INSERT INTO EMPLOYEE(NAME,EMAIL) VALUES ('AJAY','AJAY@GMAIL.COM'),
('MOHAN','MOHAN@GMAIL.COM'),('HARSH','HARSH@GMAIL.COM'),('JOHN','JOHN@GMAIL.COM');

/* FINDING ALL THE VALUES FROM THE TABLE */

SELECT * FROM EMPLOYEE;

/* DROP THE TABLE */

DROP TABLE EMPLOYEE;

/* CREATING THE SIGNUP TABLE */

CREATE TABLE SIGNUP(
ID INT IDENTITY(5555,1) PRIMARY KEY,
NAME VARCHAR(55),
EMAIL VARCHAR(55),
USERNAME VARCHAR(55),
PASSWORD VARCHAR(55),
PHONE VARCHAR(14),
DOB DATE,
GENDER VARCHAR(6),
CREATEDAT DATETIME
);

/* INSERTING VALUES IN THE SIGNUP TABLE */

INSERT INTO SIGNUP(NAME,EMAIL,USERNAME,PASSWORD,PHONE,DOB,GENDER,CREATEDAT)
VALUES('AJAY KUMAR','AJAY1@GMAIL.COM','USER1','1234','+91 1234567890','2000-04-12','MALE','2023-08-16 15:04:22'),
('MOHAN SAINI','MOHAN1@GMAIL.COM','USER2','1234','+91 1234567890','2004-04-21','MALE','2023-08-16 14:32:09'),
('NUPUR SINGH','NUPUR2@GMAIL.COM','USER3','1234','+91 1234567890','2002-01-01','FEMALE','2023-08-14 19:56:18'),
('KRATI RATOD','KRATI5@GMAIL.COM','USER4','1234','+91 1234567890','2001-10-11','FEMALE','2023-08-18 23:11:32');

/* INSERTING SINGLE VALUE IN THE TABLE */
INSERT INTO SIGNUP(NAME,EMAIL,USERNAME,PASSWORD,PHONE,DOB,GENDER,CREATEDAT)
VALUES('RAMAN KUMAR','RAMAN1@GMAIL.COM','USER1','1234','+91 1234567890','2000-04-12','MALE','2023-08-22 11:58:21');
/*GETTING ALL THE VALUES FROM THE SIGNUP VALUE*/
SELECT * FROM SIGNUP;
/*USING WHERE CLAUSE*/
SELECT * FROM SIGNUP WHERE CREATEDAT < '2023-08-18';
SELECT * FROM SIGNUP WHERE CREATEDAT < '23:11:32';

/* CREATING ADDRESS TABLE */

CREATE TABLE ADDRESS (
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
HNO INT,
CITY VARCHAR(20),
STATE VARCHAR(20),
COUNTRY VARCHAR(20),
SID INT FOREIGN KEY REFERENCES SIGNUP(ID)
);

/* INSERTING VALUES IN ADDRESS */

INSERT INTO ADDRESS(HNO,CITY,STATE,COUNTRY,SID)
VALUES (11,'DARBHANGA','BIHAR','INDIA',5555),
(33,'JAWAHAR CHOWK','JHARKHAND','INDIA',5556),
(56,'RING ROAD','DELHI','INDIA',5557),
(89,'LAL CHOWK','J&K','INDIA',5558),
(343,'VARANSI','UTTAR PRADESH','INDIA',5559);

/* PRINTING ADDRESS */

SELECT * FROM ADDRESS;
/*PERFORMING INNER JOIN*/
SELECT ADDRESS.HNO,ADDRESS.CITY,ADDRESS.STATE ,SIGNUP.ID,SIGNUP.NAME,SIGNUP.GENDER 
FROM SIGNUP
INNER JOIN ADDRESS
ON SIGNUP.ID = ADDRESS.SID;


/*TOTAL TABLES IN MY DATABASE*/
SELECT * FROM SYS.TABLES;
/*COUNTING TOTAL TABLES IN MY DATABASE*/
SELECT COUNT(*) FROM SYS.TABLES;
