USE ABHINAV;


CREATE TABLE P_EMPLOYEE(
ID INT PRIMARY KEY,
NAME VARCHAR(55)
);

CREATE TABLE ACCOUNT(
ID INT PRIMARY KEY,
E_ID INT FOREIGN KEY REFERENCES P_EMPLOYEE(ID)
);

INSERT INTO ACCOUNT(ID,E_ID) VALUES (2,2);

SELECT * FROM P_EMPLOYEE;

INSERT INTO P_EMPLOYEE (ID,NAME) VALUES (1,'AMAN');


CREATE TABLE EMPLOYEE1 (
ID INT IDENTITY(1,1) PRIMARY KEY,
NAME VARCHAR(44)
);

CREATE TABLE DEPARTMENT (
D_ID INT IDENTITY(101,1) PRIMARY KEY,
ID INT FOREIGN KEY REFERENCES EMPLOYEE1(ID),
NAME VARCHAR(55)
);

INSERT INTO EMPLOYEE1(NAME) VALUES ('RAHUL'),('ADARSH'),('GAUTAM');

SELECT * FROM EMPLOYEE1;

INSERT INTO DEPARTMENT(ID,NAME) VALUES 
(1,'IT'),(2,'FINANCE'),(3,'FIRE'),(4,'BANK');

SELECT * FROM DEPARTMENT;

INSERT INTO DEPARTMENT(ID,NAME) VALUES (99,'IT');

