USE ABHINAV;
/*CREATED TABLE R2*/
CREATE TABLE R2(
ID INT UNIQUE
);

SELECT * FROM R2;

/*INSERTED THE VALUE IN R2 TABLE*/

INSERT INTO R2(ID) VALUES (NULL);

/* NULL IS ACCEPTED ONLY ONCE BUT NOT NEXT TIME */

SELECT * FROM R2;

/* PRIMARY KEY = UNIQUE + NOT NULL */

USE ABHINAV;

CREATE TABLE R3(
ID INT PRIMARY KEY
);

INSERT INTO R3 VALUES(NULL);



/* TWO PRIMRY KEY CONCEPT*/
/*
CREATE TABLE R4(
ID INT PRIMARY KEY,
MNUMBER VARCHAR(14) PRIMARY KEY

/*
OUTPUT :- 
Msg 8110, Level 16, State 0, Line 31
Cannot add multiple PRIMARY KEY constraints to table 'R4'.
*/
);
*/

/*CREATE TABLE NAMED AS R4*/
USE ABHINAV;

CREATE TABLE R4(
ID INT,
NAME VARCHAR(55)
);

/* MODIFY TO NULL */

ALTER TABLE R4
ALTER COLUMN ID INT NOT NULL;

/* ADD PRIMARY KEY CONSTRAINT */

ALTER TABLE R4
ADD PRIMARY KEY(ID);

SELECT * FROM R4;

INSERT INTO R4(ID,NAME)
VALUES (1,'RAM'),
(2,'SHYAM');

SELECT * FROM R4;

USE ABHINAV;
CREATE TABLE R5(
ID INT NOT NULL,
NAME VARCHAR(55)
);