CREATE DATABASE BOOK_TASK;


USE BOOK_TASK;

/***************************************************** FIRST TABLE **************************************************/
/***************************************************** AUTHORS HERE **************************************************/
/* AUTHORS */

CREATE TABLE AUTHORS(
AUTHOR_ID INT IDENTITY(771,1) PRIMARY KEY,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL,
BOOK_ID INT
);

ALTER TABLE AUTHORS
ADD FOREIGN KEY(BOOK_ID) REFERENCES BOOKS(BOOK_ID);

INSERT INTO AUTHORS(FIRST_NAME,LAST_NAME,BOOK_ID)
VALUES('HARISH','CHANDRA VERMA',1001);

INSERT INTO AUTHORS(FIRST_NAME,LAST_NAME,BOOK_ID)
VALUES('VALMIKI','Ratnakkardah',1003);

SELECT * FROM AUTHORS;

/***************************************************** SECOND TABLE **************************************************/
/***************************************************** PUBLISHERS HERE **************************************************/
/* PUBLISHERS */
CREATE TABLE PUBLISHERS(
PULISH_ID INT IDENTITY(901,1) PRIMARY KEY,
COUNTRY VARCHAR(100),
BOOK_ID INT
);

ALTER TABLE PUBLISHERS
ADD FOREIGN KEY(BOOK_ID) REFERENCES BOOKS(BOOK_ID);

INSERT INTO PUBLISHERS(COUNTRY,BOOK_ID)
VALUES('INDIA',1001);

INSERT INTO PUBLISHERS(COUNTRY,BOOK_ID)
VALUES('INDIA',1003);

SELECT * FROM PUBLISHERS;




/***************************************************** THIRD TABLE **************************************************/
/***************************************************** BOOKS HERE **************************************************/

/* THIRD TABLE */

/* CREATE THE BOOK TABLE */

CREATE TABLE BOOKS (
BOOK_ID INT IDENTITY(1001,1) PRIMARY KEY,
TITLE VARCHAR(200) NOT NULL ,
ISBN VARCHAR(100) NOT NULL,
GENRE VARCHAR(50) NOT NULL,
TYPE_BOOK VARCHAR(50) NOT NULL,
PUBLICATION_YEAR DATE NOT NULL,
PRICE MONEY NOT NULL,
CONDITION VARCHAR(55) NOT NULL
);

/*
ALTER TABLE BOOKS
ADD FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID);

ALTER TABLE BOOKS
ADD FOREIGN KEY(PUBLISHER_ID) REFERENCES PUBLISHERS(PULISH_ID);

ALTER TABLE BOOKS 
DROP CONSTRAINT FK__BOOKS__AUTHOR_ID__59FA5E80;

ALTER TABLE BOOKS
DROP CONSTRAINT FK__BOOKS__PUBLISHER__59063A47;
*/

/** ALTER AND DELETE TIGHTLY LOCKED **/

ALTER TABLE BOOKS
DROP COLUMN AUTHOR_ID;

ALTER TABLE BOOKS
DROP COLUMN PUBLISHER_ID;

INSERT INTO BOOKS(AUTHOR_ID,PUBLISHER_ID,TITLE,ISBN,GENRE,TYPE_BOOK,PUBLICATION_YEAR,PRICE,CONDITION)
VALUES('CONCEPTS OF PHYSICS','12221','EDUCATION','EDUCATION','1992-05-21',788,'A+');

INSERT INTO BOOKS(TITLE,ISBN,GENRE,TYPE_BOOK,PUBLICATION_YEAR,PRICE,CONDITION)
VALUES('RAMAYAN','12222','CULTURAL','CULTURAL','1990-05-21',199,'A+');

SELECT * FROM BOOKS;




/*************************************************************** FOURTH INVENTORY ****************************************************************/

CREATE TABLE INVENTORY(
INVENTORY_ID INT IDENTITY(661,1),
BOOK_ID INT,
STOCK_LEVEL_USED VARCHAR(50),
STOCK_LEVEL_NEW VARCHAR(50)
);

ALTER TABLE INVENTORY
ADD FOREIGN KEY(BOOK_ID) REFERENCES BOOKS(BOOK_ID);


INSERT INTO INVENTORY(BOOK_ID,STOCK_LEVEL_USED,STOCK_LEVEL_NEW)
VALUES(1001,'HALF','FULL');

INSERT INTO INVENTORY(BOOK_ID,STOCK_LEVEL_USED,STOCK_LEVEL_NEW)
VALUES(1003,'EMPTY','EMPTY');

SELECT * FROM INVENTORY;






/***************************************************** FIFTH TABLE **************************************************/
/***************************************************** CUSTOMERS HERE **************************************************/
/* CREATE CUSTOMERS TABLE PRIMARY TABLE */

/*  OUR MAIN TABLE */ 

CREATE TABLE CUSTOMERS(
CUST_ID INT IDENTITY(101,1) PRIMARY KEY,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL,
STREET_NUMBER VARCHAR(100) NOT NULL,
STREET_NAME VARCHAR(100) NOT NULL,
POSTAL_CODE VARCHAR(100) NOT NULL,
PROVINCE VARCHAR(100) NOT NULL,
COUNTRY VARCHAR(100) NOT NULL,
PHONENUMBER VARCHAR(14) NOT NULL,
REGISTER_DATE DATETIME NOT NULL
);


/* INSERT VALUES INTO CUSTOMERS */

INSERT INTO CUSTOMERS(FIRST_NAME,LAST_NAME,STREET_NUMBER,STREET_NAME,POSTAL_CODE,PROVINCE,COUNTRY,PHONENUMBER,REGISTER_DATE)
VALUES ('NARENDRA','MODI','ROAD NUMBER 24/36','PARLIAMENT ROAD','110011','DELHI','INDIA','1800 2422 2929',GETDATE());

INSERT INTO CUSTOMERS(FIRST_NAME,LAST_NAME,STREET_NUMBER,STREET_NAME,POSTAL_CODE,PROVINCE,COUNTRY,PHONENUMBER,REGISTER_DATE)
VALUES ('RAHUL','GANDHI','OPPOSITION ROAD 104','JAISALMER ROAD','110012','NEW DELHI','INDIA','1800 2422 3443',GETDATE());

INSERT INTO CUSTOMERS(FIRST_NAME,LAST_NAME,STREET_NUMBER,STREET_NAME,POSTAL_CODE,PROVINCE,COUNTRY,PHONENUMBER,REGISTER_DATE)
VALUES ('MAMTA','BANARJEE','GM ROAD 4','ALL INDIA TRINMOOL PARTY ROAD','700123','NEW TOWN KOLKATA','INDIA','1800 5566 9129',GETDATE());



SELECT * FROM CUSTOMERS;







/***************************************************** SIX TABLE **************************************************/
/***************************************************** ORDER_ITEM HERE **************************************************/
/* ORDER ITEM */

CREATE TABLE ORDER_ITEM(
ORDER_ID INT IDENTITY(501,1) PRIMARY KEY,
BOOK_ID INT,
QUANTITY INT NOT NULL,
PRICE MONEY NOT NULL
);

ALTER TABLE ORDER_ITEM
ADD FOREIGN KEY(BOOK_ID) REFERENCES BOOKS(BOOK_ID);

INSERT INTO ORDER_ITEM(BOOK_ID,QUANTITY,PRICE)
VALUES(1001,2,1523.92);

INSERT INTO ORDER_ITEM(BOOK_ID,QUANTITY,PRICE)
VALUES(1003,5,133.92);

SELECT * FROM ORDER_ITEM;


/***************************************************** SEVEN TABLE **************************************************/
/***************************************************** ORDERS HERE **************************************************/

CREATE TABLE ORDERS(
ORDER_ID INT IDENTITY(21,1) PRIMARY KEY,
CUST_ID INT,
ORDERDATE DATETIME NOT NULL,
SUBTOTAL MONEY NOT NULL,
SHIPPING VARCHAR(55),
TOTAL MONEY NOT NULL,
FOREIGN KEY(CUST_ID) REFERENCES CUSTOMERS(CUST_ID)
);

ALTER TABLE ORDERS
ADD FOREIGN KEY(ORDER_ITEM) REFERENCES ORDER_ITEM(ORDER_ID);

/* INSERT VALUES INTO ORDERS */

INSERT INTO ORDERS(CUST_ID,ORDERDATE,SUBTOTAL,SHIPPING,TOTAL)
VALUES(101,GETDATE(),112.24,'DELHI',5665.89);

INSERT INTO ORDERS(CUST_ID,ORDERDATE,SUBTOTAL,SHIPPING,TOTAL)
VALUES(102,GETDATE(),144.24,'DELHI',165.89);

SELECT * FROM ORDERS;





